export const products = [
  {
    name: 'Botanical Glow Oil',
    slug: 'botanical-glow-oil',
    description:
      'A luminous facial oil designed to restore softness, radiance, and barrier comfort in one easy ritual. Rosehip, jojoba, and calendula melt into the skin to leave a healthy satin finish, while supporting daily hydration for dry or tired complexions.',
    shortDescription: 'Vitamin-rich facial oil for luminous, hydrated skin.',
    price: 68,
    compareAtPrice: 82,
    category: 'Facial Oils',
    productType: 'Facial Oil',
    skinConcerns: ['Dryness', 'Dullness', 'Barrier Support'],
    ingredients: ['Rosehip Seed Oil', 'Jojoba Oil', 'Calendula Extract', 'Vitamin E', 'Squalane'],
    benefits: ['Boosts glow', 'Nourishes deeply', 'Softens texture', 'Supports skin barrier'],
    howToUse: 'Warm 2–4 drops between your palms and press gently onto clean, damp skin morning and night.',
    images: [
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&q=80',
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=1200&q=80',
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80',
    stock: 110,
    sku: 'GT-BO-001',
    rating: 4.9,
    reviewCount: 92,
    featured: true,
    bestSeller: true,
    newArrival: false,
    tags: ['glow', 'botanical', 'hydrating', 'organic', 'organic-favorite', 'dermatologist-recommended', 'all-skin-types', 'trending', 'natural-essential'],
    options: [{ name: 'Size', values: ['30ml', '50ml', '100ml'] }],
    variants: [
      { sku: 'GT-BO-001-30', options: { Size: '30ml' }, price: 68, compareAtPrice: 82, stock: 48, lowStockThreshold: 8, weight: '30ml', images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80'], status: 'active' },
      { sku: 'GT-BO-001-50', options: { Size: '50ml' }, price: 94, compareAtPrice: 110, stock: 32, lowStockThreshold: 8, weight: '50ml', images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=900&q=80'], status: 'active' },
      { sku: 'GT-BO-001-100', options: { Size: '100ml' }, price: 128, compareAtPrice: 150, stock: 18, lowStockThreshold: 8, weight: '100ml', images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Dew Restore Serum',
    slug: 'dew-restore-serum',
    description:
      'A silky serum built for plump, healthy-looking skin. Hyaluronic acid, niacinamide, and white tea help strengthen moisture balance while smoothing the look of fine lines and restoring a fresh, radiant finish.',
    shortDescription: 'Hydrating serum for dewy, even, refreshed skin.',
    price: 72,
    compareAtPrice: 88,
    category: 'Serums',
    productType: 'Serum',
    skinConcerns: ['Dehydration', 'Fine Lines', 'Uneven Tone'],
    ingredients: ['Hyaluronic Acid', 'Niacinamide', 'White Tea Extract', 'Panthenol', 'Peptides'],
    benefits: ['Locks in hydration', 'Smooths texture', 'Improves radiance', 'Supports firmness'],
    howToUse: 'Apply 2–3 drops after cleansing and before moisturizer. Press gently until absorbed.',
    images: [
      'https://images.unsplash.com/photo-1617897903246-719242758050?w=1200&q=80',
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=900&q=80',
    stock: 90,
    sku: 'GT-DS-002',
    rating: 4.8,
    reviewCount: 76,
    featured: true,
    bestSeller: true,
    newArrival: false,
    tags: ['hydrating', 'serum', 'dewy', 'brightening', 'dermatologist-recommended', 'all-skin-types', 'trending'],
    options: [{ name: 'Size', values: ['30ml', '50ml'] }],
    variants: [
      { sku: 'GT-DS-002-30', options: { Size: '30ml' }, price: 72, compareAtPrice: 88, stock: 36, lowStockThreshold: 8, weight: '30ml', images: ['https://images.unsplash.com/photo-1617897903246-719242758050?w=900&q=80'], status: 'active' },
      { sku: 'GT-DS-002-50', options: { Size: '50ml' }, price: 98, compareAtPrice: 118, stock: 22, lowStockThreshold: 8, weight: '50ml', images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Rose Cleanse Ritual',
    slug: 'rose-cleanse-ritual',
    description:
      'A gentle cleansing oil that melts away sunscreen, makeup, and daily buildup without compromising the skin barrier. Rose water and camellia offer a soft, balanced finish that feels comforting from the first cleanse to the last rinse.',
    shortDescription: 'Gentle cleansing oil for soft, balanced skin.',
    price: 44,
    compareAtPrice: 54,
    category: 'Cleansers',
    productType: 'Cleanser',
    skinConcerns: ['Sensitivity', 'Makeup Removal', 'Congestion'],
    ingredients: ['Camellia Oil', 'Rose Water', 'Grapeseed Oil', 'Sunflower Oil', 'Lavender'],
    benefits: ['Removes impurities', 'Maintains hydration', 'Calms sensitivity', 'No tightness'],
    howToUse: 'Massage onto dry skin, then add water to emulsify and rinse thoroughly. Follow with toner or mist.',
    images: [
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=1200&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=900&q=80',
    stock: 120,
    sku: 'GT-CL-003',
    rating: 4.7,
    reviewCount: 68,
    featured: true,
    bestSeller: false,
    newArrival: false,
    tags: ['gentle', 'cleanser', 'rose', 'organic', 'natural-essential', 'all-skin-types', 'sensitive-skin'],
    options: [{ name: 'Size', values: ['120ml', '200ml'] }],
    variants: [
      { sku: 'GT-CL-003-120', options: { Size: '120ml' }, price: 44, compareAtPrice: 54, stock: 52, lowStockThreshold: 10, weight: '120ml', images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=900&q=80'], status: 'active' },
      { sku: 'GT-CL-003-200', options: { Size: '200ml' }, price: 58, compareAtPrice: 70, stock: 34, lowStockThreshold: 10, weight: '200ml', images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Cloud Ceramide Cream',
    slug: 'cloud-ceramide-cream',
    description:
      'A cushiony daily moisturizer that creates a soft, cloudlike finish while reinforcing hydration and comfort. Ceramides, squalane, and oat help replenish the skin barrier and reduce the feeling of tightness.',
    shortDescription: 'Comforting cream for soft, hydrated, resilient skin.',
    price: 62,
    compareAtPrice: 74,
    category: 'Moisturizers',
    productType: 'Moisturizer',
    skinConcerns: ['Dryness', 'Sensitivity', 'Barrier Repair'],
    ingredients: ['Ceramides', 'Squalane', 'Oat Extract', 'Hyaluronic Acid', 'Colostrum'],
    benefits: ['Restores barrier', 'Hydrates long-lasting', 'Calms tightness', 'Soft finish'],
    howToUse: 'Apply to clean skin morning and night. Massage gently over face and neck.',
    images: [
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=1200&q=80',
      'https://images.unsplash.com/photo-1617897903246-719242758050?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=900&q=80',
    stock: 88,
    sku: 'GT-MO-004',
    rating: 4.9,
    reviewCount: 84,
    featured: true,
    bestSeller: true,
    newArrival: false,
    tags: ['barrier', 'moisturizer', 'ceramide', 'comfort', 'dermatologist-recommended', 'sensitive-skin', 'all-skin-types', 'organic-favorite'],
    options: [{ name: 'Size', values: ['50ml', '100ml'] }],
    variants: [
      { sku: 'GT-MO-004-50', options: { Size: '50ml' }, price: 62, compareAtPrice: 74, stock: 42, lowStockThreshold: 10, weight: '50ml', images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=900&q=80'], status: 'active' },
      { sku: 'GT-MO-004-100', options: { Size: '100ml' }, price: 88, compareAtPrice: 104, stock: 26, lowStockThreshold: 10, weight: '100ml', images: ['https://images.unsplash.com/photo-1617897903246-719242758050?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Pearl Bright Mask',
    slug: 'pearl-bright-mask',
    description:
      'A polish-and-brighten clay mask that gently lifts away pollution, softness, and dullness. Pearl powder, rice, and aloe leave the complexion looking fresh, refined, and softly luminous without stripping the skin.',
    shortDescription: 'Radiance-boosting mask for a smoother, brighter finish.',
    price: 46,
    compareAtPrice: 58,
    category: 'Face Masks',
    productType: 'Mask',
    skinConcerns: ['Dullness', 'Texture', 'Congestion'],
    ingredients: ['Kaolin Clay', 'Pearl Powder', 'Rice Extract', 'Aloe Vera', 'Turmeric'],
    benefits: ['Brightens appearance', 'Refines texture', 'Deep cleans without stripping', 'Smooths finish'],
    howToUse: 'Apply an even layer to clean skin, leave for 10–12 minutes, and rinse with lukewarm water.',
    images: [
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&q=80',
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80',
    stock: 72,
    sku: 'GT-MA-005',
    rating: 4.8,
    reviewCount: 63,
    featured: false,
    bestSeller: true,
    newArrival: false,
    tags: ['mask', 'brightening', 'clay', 'glow', 'organic-favorite', 'trending'],
    options: [{ name: 'Size', values: ['50g', '100g'] }],
    variants: [
      { sku: 'GT-MA-005-50', options: { Size: '50g' }, price: 46, compareAtPrice: 58, stock: 34, lowStockThreshold: 8, weight: '50g', images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80'], status: 'active' },
      { sku: 'GT-MA-005-100', options: { Size: '100g' }, price: 64, compareAtPrice: 78, stock: 18, lowStockThreshold: 8, weight: '100g', images: ['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Rose Water Mist',
    slug: 'rose-water-mist',
    description:
      'A refreshing rose mist for midday hydration and a quick reset. Rose water, aloe, and cucumber work together to calm and plump the skin while creating a soft, dewy finish that feels anything but heavy.',
    shortDescription: 'Hydrating mist for a fresh, calm, dewy finish.',
    price: 34,
    compareAtPrice: 42,
    category: 'Toners',
    productType: 'Mist',
    skinConcerns: ['Dehydration', 'Sensitivity', 'Dullness'],
    ingredients: ['Rose Water', 'Cucumber Extract', 'Aloe Vera', 'Glycerin', 'Chamomile'],
    benefits: ['Refreshes instantly', 'Hydrates gently', 'Calms skin', 'Preps complexion'],
    howToUse: 'Mist over clean skin or after makeup for a fresh reset. Layer as needed throughout the day.',
    images: [
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=1200&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=900&q=80',
    stock: 150,
    sku: 'GT-TM-006',
    rating: 4.6,
    reviewCount: 58,
    featured: false,
    bestSeller: true,
    newArrival: false,
    tags: ['mist', 'rose', 'hydrating', 'refreshing', 'natural-essential', 'all-skin-types', 'sensitive-skin'],
    options: [{ name: 'Size', values: ['100ml', '200ml'] }],
    variants: [
      { sku: 'GT-TM-006-100', options: { Size: '100ml' }, price: 34, compareAtPrice: 42, stock: 72, lowStockThreshold: 12, weight: '100ml', images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=900&q=80'], status: 'active' },
      { sku: 'GT-TM-006-200', options: { Size: '200ml' }, price: 48, compareAtPrice: 58, stock: 52, lowStockThreshold: 12, weight: '200ml', images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Caffeine Eye Elixir',
    slug: 'caffeine-eye-elixir',
    description:
      'A lightweight eye treatment created to brighten and calm the look of tired eyes. Caffeine, peptides, and cucumber help reduce the appearance of puffiness while delivering a soft, hydrated finish around the delicate eye area.',
    shortDescription: 'Gentle eye treatment for a rested, bright finish.',
    price: 54,
    compareAtPrice: 66,
    category: 'Serums',
    productType: 'Eye Treatment',
    skinConcerns: ['Puffiness', 'Dark Circles', 'Fine Lines'],
    ingredients: ['Caffeine', 'Peptides', 'Cucumber Extract', 'Hyaluronic Acid', 'Green Tea'],
    benefits: ['Reduces puffiness', 'Brightens look', 'Softens fine lines', 'Hydrates delicately'],
    howToUse: 'Press a small amount around the under-eye area using the ring finger. Use morning and night.',
    images: [
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&q=80',
      'https://images.unsplash.com/photo-1617897903246-719242758050?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80',
    stock: 84,
    sku: 'GT-EY-007',
    rating: 4.8,
    reviewCount: 49,
    featured: true,
    bestSeller: false,
    newArrival: true,
    tags: ['eye-care', 'brightening', 'caffeine', 'anti-fatigue', 'trending', 'dermatologist-recommended'],
    options: [{ name: 'Size', values: ['15ml', '30ml'] }],
    variants: [
      { sku: 'GT-EY-007-15', options: { Size: '15ml' }, price: 54, compareAtPrice: 66, stock: 38, lowStockThreshold: 8, weight: '15ml', images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80'], status: 'active' },
      { sku: 'GT-EY-007-30', options: { Size: '30ml' }, price: 78, compareAtPrice: 94, stock: 21, lowStockThreshold: 8, weight: '30ml', images: ['https://images.unsplash.com/photo-1617897903246-719242758050?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Velvet Body Ritual Oil',
    slug: 'velvet-body-ritual-oil',
    description:
      'A body oil treated with almond, sesame, and apricot oils to leave skin velvety-soft and lightly luminous after every shower or evening ritual. It settles beautifully on warm skin and leaves a subtle botanical finish.',
    shortDescription: 'Silky body oil for soft, luminous skin.',
    price: 48,
    compareAtPrice: 60,
    category: 'Body Care',
    productType: 'Body Oil',
    skinConcerns: ['Dryness', 'Flaky Skin', 'Roughness'],
    ingredients: ['Sweet Almond Oil', 'Apricot Kernel Oil', 'Sesame Seed Oil', 'Vitamin E', 'Vanilla'],
    benefits: ['Nourishes deeply', 'Improves softness', 'Leaves a satin finish', 'Comforts dry areas'],
    howToUse: 'Apply to damp skin after bathing, focusing on elbows, knees, and any dry patches.',
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=1200&q=80',
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=900&q=80',
    stock: 96,
    sku: 'GT-BD-008',
    rating: 4.7,
    reviewCount: 55,
    featured: false,
    bestSeller: true,
    newArrival: false,
    tags: ['body-care', 'body-oil', 'hydrating', 'velvet', 'natural-essential', 'organic-favorite'],
    options: [{ name: 'Size', values: ['100ml', '200ml'] }],
    variants: [
      { sku: 'GT-BD-008-100', options: { Size: '100ml' }, price: 48, compareAtPrice: 60, stock: 44, lowStockThreshold: 10, weight: '100ml', images: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=900&q=80'], status: 'active' },
      { sku: 'GT-BD-008-200', options: { Size: '200ml' }, price: 68, compareAtPrice: 82, stock: 28, lowStockThreshold: 10, weight: '200ml', images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Nectar Lip Balm',
    slug: 'nectar-lip-balm',
    description:
      'A nourishing lip treatment made with shea, beeswax, and botanical oils to protect and soften lips through every season. It glides on smoothly without any greasy residue and leaves a comforted finish.',
    shortDescription: 'Nourishing lip balm for soft, protected lips.',
    price: 18,
    compareAtPrice: 24,
    category: 'Lip Care',
    productType: 'Lip Balm',
    skinConcerns: ['Dryness', 'Chapping'],
    ingredients: ['Shea Butter', 'Beeswax', 'Coconut Oil', 'Vitamin E', 'Vanilla'],
    benefits: ['Softens lips', 'Protects from dryness', 'Hydrates', 'Smooth finish'],
    howToUse: 'Apply as needed throughout the day or before bed for overnight comfort.',
    images: [
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=1200&q=80',
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=900&q=80',
    stock: 240,
    sku: 'GT-LP-009',
    rating: 4.9,
    reviewCount: 110,
    featured: false,
    bestSeller: true,
    newArrival: false,
    tags: ['lip-care', 'balm', 'nourishing', 'daily-essentials', 'natural-essential', 'all-skin-types'],
    options: [{ name: 'Size', values: ['10g', '20g'] }],
    variants: [
      { sku: 'GT-LP-009-10', options: { Size: '10g' }, price: 18, compareAtPrice: 24, stock: 140, lowStockThreshold: 20, weight: '10g', images: ['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=900&q=80'], status: 'active' },
      { sku: 'GT-LP-009-20', options: { Size: '20g' }, price: 26, compareAtPrice: 34, stock: 78, lowStockThreshold: 20, weight: '20g', images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Golden Clay Polish',
    slug: 'golden-clay-polish',
    description:
      'A gentle exfoliating clay mask that smooths away dullness and leaves the skin looking fresher, softer, and more even. Golden clay, honey, and oat combine in a refined treatment that supports a polished, healthy glow.',
    shortDescription: 'Detoxifying polish for smoother, brighter skin.',
    price: 52,
    compareAtPrice: 64,
    category: 'Face Masks',
    productType: 'Exfoliating Mask',
    skinConcerns: ['Texture', 'Congestion', 'Dullness'],
    ingredients: ['Golden Clay', 'Raw Honey', 'Oat Powder', 'Turmeric', 'Kaolin'],
    benefits: ['Smooths texture', 'Boosts brightness', 'Refines pores', 'Balances skin'],
    howToUse: 'Apply a thin layer to clean skin, leave for 8–10 minutes, and rinse away with lukewarm water.',
    images: [
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=1200&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=900&q=80',
    stock: 66,
    sku: 'GT-MS-010',
    rating: 4.7,
    reviewCount: 44,
    featured: false,
    bestSeller: false,
    newArrival: true,
    tags: ['mask', 'exfoliating', 'detox', 'brightening', 'organic-favorite', 'trending'],
    options: [{ name: 'Size', values: ['50g', '100g'] }],
    variants: [
      { sku: 'GT-MS-010-50', options: { Size: '50g' }, price: 52, compareAtPrice: 64, stock: 32, lowStockThreshold: 8, weight: '50g', images: ['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=900&q=80'], status: 'active' },
      { sku: 'GT-MS-010-100', options: { Size: '100g' }, price: 72, compareAtPrice: 88, stock: 19, lowStockThreshold: 8, weight: '100g', images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
  {
    name: 'Night Recovery Balm',
    slug: 'night-recovery-balm',
    description:
      'A rich overnight balm that cushions the skin with ceramides, shea, and botanical oils to help repair the look of dryness while you sleep. Wake up to a velvety, comforted complexion and a calmer texture.',
    shortDescription: 'Overnight balm for deep repair and comfort.',
    price: 58,
    compareAtPrice: 70,
    category: 'Facial Oils',
    productType: 'Balm',
    skinConcerns: ['Dryness', 'Barrier Repair', 'Comfort'],
    ingredients: ['Shea Butter', 'Ceramides', 'Evening Primrose', 'Rose Absolute', 'Jojoba'],
    benefits: ['Deeply comforting', 'Supports barrier repair', 'Softens rough patches', 'Restorative overnight care'],
    howToUse: 'Warm a small amount between palms and press onto clean skin as the final step in your evening ritual.',
    images: [
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=1200&q=80',
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=900&q=80',
    stock: 76,
    sku: 'GT-NR-011',
    rating: 4.8,
    reviewCount: 54,
    featured: false,
    bestSeller: false,
    newArrival: true,
    tags: ['night-care', 'repair', 'balm', 'overnight', 'dermatologist-recommended', 'organic-favorite', 'trending'],
    options: [{ name: 'Size', values: ['30g', '60g'] }],
    variants: [
      { sku: 'GT-NR-011-30', options: { Size: '30g' }, price: 58, compareAtPrice: 70, stock: 40, lowStockThreshold: 8, weight: '30g', images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=900&q=80'], status: 'active' },
      { sku: 'GT-NR-011-60', options: { Size: '60g' }, price: 82, compareAtPrice: 98, stock: 18, lowStockThreshold: 8, weight: '60g', images: ['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=900&q=80'], status: 'active' },
    ],
    status: 'active',
  },
];
