import { z } from 'zod';

const productVariantSchema = z.object({
  _id: z.string().optional(),
  sku: z.string().min(1),
  options: z.record(z.string(), z.string()),
  price: z.number().min(0).optional(),
  compareAtPrice: z.number().min(0).optional(),
  stock: z.number().int().min(0).default(0),
  lowStockThreshold: z.number().int().min(0).default(5),
  weight: z.string().optional(),
  image: z.string().optional(),
  images: z.array(z.string()).optional(),
  barcode: z.string().optional(),
  status: z.enum(['active', 'inactive', 'out_of_stock']).optional(),
});

export const productSchema = z.object({
  name: z.string().min(2).max(200),
  description: z.string().min(10),
  shortDescription: z.string().min(10).max(300),
  price: z.number().positive(),
  compareAtPrice: z.number().positive().optional(),
  category: z.string().min(1),
  productType: z.string().min(1),
  skinConcerns: z.array(z.string()).optional(),
  ingredients: z.array(z.string()).optional(),
  benefits: z.array(z.string()).optional(),
  howToUse: z.string().optional(),
  images: z.array(z.string()).optional(),
  thumbnail: z.string().min(1),
  stock: z.number().int().min(0),
  sku: z.string().min(1),
  featured: z.boolean().optional(),
  bestSeller: z.boolean().optional(),
  newArrival: z.boolean().optional(),
  tags: z.array(z.string()).optional(),
  options: z.array(z.object({
    name: z.string().min(1),
    values: z.array(z.string().min(1)).min(1),
  })).optional(),
  variants: z.array(productVariantSchema).optional(),
  status: z.enum(['active', 'draft', 'archived']).optional(),
});

export const productQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(50).default(12),
  category: z.string().optional(),
  productType: z.string().optional(),
  skinConcern: z.string().optional(),
  ingredient: z.string().optional(),
  minPrice: z.coerce.number().min(0).optional(),
  maxPrice: z.coerce.number().min(0).optional(),
  rating: z.coerce.number().min(0).max(5).optional(),
  inStock: z.coerce.boolean().optional(),
  featured: z.coerce.boolean().optional(),
  bestSeller: z.coerce.boolean().optional(),
  newArrival: z.coerce.boolean().optional(),
  tags: z.string().optional(),
  onSale: z.coerce.boolean().optional(),
  search: z.string().optional(),
  sort: z.enum(['newest', 'price-asc', 'price-desc', 'rating', 'name']).default('newest'),
});
